# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fad688bcb1be9792e508d34d5fa9b1bfaa662abc4460bebcebae365ca05c0b7ef1cec6c9f6e473b96817292f4dd22c408e33491fd76e89a1da516b78583615ea

test:
  secret_key_base: 6e99546a018f8b2023725d20f55903573a9889d6bbf4b430b0ded108e63b1960620f024c0d6a3bec3a3ec9e9fbc74daba3260ec8fbe419117b047602b6043667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
